#!/bin/bash
#--------------------------------------------
# Description: Linux Lite Auto Login Dialogue
# Authors: Jerry Bezencon, Ralphy
# Website: https://www.linuxliteos.com
#--------------------------------------------

# variables
APPNAME="Enable Auto Login"
ic="/usr/share/icons/zenity-llcc.png"

while (true); do
# Main window dialogue.
zenity --question --icon-name="info" --window-icon="$ic" --ok-label="Enable Auto Login" --cancel-label="Quit" --width="400" --height=60 --title="$APPNAME" \
       --text="\n                       <b>You are about to Enable Auto Login</b>\n \

Next time your computer is restarted you will be automatically signed in. \n \

<b>Important</b> The Auto Login feature is provided as a convenience. However, this feature may be a security risk. \
When you Enable Auto Login, anyone who can physically obtain access to the computer can gain access to all the computer's contents, \
including any networks it is connected to. This setting is recommended only for cases in which the computer is physically secured."

if [ "$?" -eq "0" ]; then
    gksu --message '
      <b>Your password is required to Enable Auto Login</b> 

Please enter your password to continue, or press Cancel to exit now.' "sed -i "s/autologin-user=linux/autologin-user=$USER/g" /etc/lightdm/lightdm.conf"
        if [ "${PIPESTATUS[0]}" -eq "0" ]; then
                zenity --info --title="$APPNAME" --window-icon=$ic --text="\nAuto Login has been Enabled!"
                exit 0
        else
                zenity --error --width="200" --title="$APPNAME - Error" --text="\nAuto Login could not be enabled."
                continue
        fi
else
        exit 0
fi
done
exit 0
