#!/bin/bash
#--------------------------------------------
# Description: Linux Lite Auto Login Dialogue
# Authors: Jerry Bezencon, Ralphy
# Website: https://www.linuxliteos.com
#--------------------------------------------

# variables
APPNAME="Enable Auto Login"
ic="/usr/share/icons/zenity-llcc.png"
EALUSER=$(sudo -u ${SUDO_USER:-$USER} whoami)

if [ $EUID -ne 0 ]; then
    gksu -m '
<b>Enable Auto Login requires Administrative privileges</b> 


            Please enter your password to continue.' bash $0
   exit
else :
fi
while (true); do
# Main window dialogue.
zenity --question --icon-name="info" --window-icon="$ic" --ok-label="$APPNAME" --cancel-label="Cancel" --width="400" --height="60" --title="$APPNAME" \
       --text="\n                       <b>You are about to $APPNAME</b>\n \

Next time your computer is restarted you will be automatically signed in. \n \

<b>Important</b> The Auto Login feature is provided as a convenience. However, this feature may be a security risk. \
When you Enable Auto Login, anyone who can physically obtain access to the computer can gain access to all the computer's contents, \
including any networks it is connected to. This setting is recommended only for cases in which the computer is physically secured."

if [ "$?" -eq "0" ]; then
    sed -i "s/autologin-user=.*/autologin-user=$EALUSER/g" /etc/lightdm/lightdm.conf
        if [ "${PIPESTATUS[0]}" -eq "0" ]; then
                zenity --info --width="200" --height=40 --timeout=3 --title="   $APPNAME" --window-icon=$ic --text="\nAuto Login has been Enabled!"
                exit 0
        else
                zenity --error --width="280" --height="40" --title="$APPNAME - Error" --text="\nAn error occurred while enabling Auto Login."
                continue
        fi
else
        exit 0
fi
done
exit 0