#!/bin/bash
#--------------------------------------------
# Description: Linux Lite Network Shares GUI Dialogue
# Author: Jerry Bezencon 2015, Ralphy
# Website: https://www.linuxliteos.com
#--------------------------------------------

# variables
APPNAME="Network Share Settings"
ic="/usr/share/icons/zenity-llcc.png"
#EALUSER=$(sudo -u ${SUDO_USER:-$USER} whoami)
if [ $EUID -ne 0 ]; then
    gksu -m '
<b>Editing Share Settings requires Administrative privileges</b>


                Please enter your password to continue.' bash $0
   exit
else :
fi

zenity --question --width="360"  --icon-name="info" --ok-label="Edit Share Settings" --cancel-label="Cancel" --title="$APPNAME" --window-icon="$ic" \
       --text="\nYou are about to configure Network Share Settings.\n\n\
Network Share Settings will open in your text editor. <b>Apply changes carefully.</b>\n\n\
After you finish editing Network Share Settings, its services must be restarted.\n"

while (true); do
if [ "$?" -eq "0" ]; then
EDITSHARES=$(xdg-open /etc/samba/smb.conf )
unset EDITSHARES

zenity --question --width="300"  --icon-name="info" --ok-label="Edit again" --cancel-label="Restart Share Services" --title="$APPNAME" --window-icon="$ic" \
       --text="\nReady to restart the Network Share Services or would you like to review the settings one more time?"

    if [ "$?" -eq "0" ]; then
        continue
    else
        RESTARTSHARES=$( stdbuf -oL /bin/bash \-c '(service smbd restart && service nmbd restart && sleep 1 )' 2>&1 |
        stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' | 
        zenity --progress --title="Restarting Network Share Services..." --pulsate --no-cancel --width=340 --auto-close )
        unset RESTARTSHARES
            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                zenity --error \
                       --title="Error" --text="$APPNAME configuration failed."
                exit 0
            else
                zenity --info timeout=3 --title="$APPNAME" --window-icon="$ic" --width="220" --text="\nYour settings have been applied."
                exit 0
            fi
    fi
else
    exit 0
fi
done
exit 0