#!/bin/bash
set -e
# Postinst script for bug fixes for 3.x Series
# Fix 'virtualbox kernel service is not running'
# As reported here - https://www.linuxliteos.com/forums/other/vboxclient-the-virtualbox-kernel-service-is-not-running/
# Fix is here - https://www.linuxliteos.com/forums/other/vboxclient-the-virtualbox-kernel-service-is-not-running/msg19295/#msg19295
FILE="/etc/X11/Xsession.d/98vboxadd-xclient"
[ -s "$FILE" ] && sed -i "s/notify-send/echo/g" $FILE

# BUG - Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
test -e ["/etc/apt/apt.conf.d/20auto-upgrades.ucf-dist"] || rm -rf /etc/apt/apt.conf.d/20auto-upgrades.ucf-dist

# File ownership
chown root:root /boot/startupsound.wav
chown root:root /etc/apt/apt.conf.d/local
chown root:root /etc/skel -R
chown root:root /usr/bin/lite-software
chown root:root /usr/share/applications/* -R
chown root:root /usr/share/icons/Faenza* -R
chown root:root /usr/share/liteappsicons -R
chown root:root /usr/share/icons/* -R
chown root:root /usr/scripts -R
chown root:root /usr/share/lightdm/lightdm.conf.d/50-linuxlite.conf
# File permissions
chmod 644 /boot/startupsound.wav
chmod 644 /etc/apt/apt.conf.d/local
chmod 644 /usr/share/lightdm/lightdm.conf.d/50-linuxlite.conf
chmod 755 /usr/scripts -R

# /usr/share/applications - Lite applications permissions
APP_FOLDER="/usr/share/applications"
APPS_LIST=(createsysreport.desktop
litecleaner.desktop
liteinfo.desktop
litesoftware.desktop
lite-updatesnotify.desktop
liteupgrade.desktop
liteusermanager.desktop
lite_welcome.desktop
netsharesettings.desktop
networkconnections.desktop
support.desktop)

for _APP in ${APPS_LIST[*]}; do
  if [ -f "$APP_FOLDER/$_APP" ]; then chmod 644 "$APP_FOLDER/$_APP"; else :; fi
done

## folder MUST have correct permissions for systems with multiple accounts
find /etc/skel -type d -exec chmod 755 {} \;
find /etc/skel -type f -exec chmod 644 {} \;

if [ -d "/etc/skel/.conky" ]; then
   if [ -f "/etc/skel/.conky/start" ]; then chmod +x /etc/skel/.conky/start; else :; fi
   if [ -f "/etc/skel/.conky/updates" ]; then chmod +x /etc/skel/.conky/updates; else :; fi
else :; fi

# UPDATE .desktop files
[ -e "/etc/skel/.local/share/applications/exo-file-manager.desktop" ] && sed -i 's#Exec=.*#Exec=/usr/scripts/updates-gui#' /etc/skel/.local/share/applications/exo-file-manager.desktop # Install Updates

# Remove old files if exist
if [ -d "/usr/share/litesoftware" ]; then rm -rf /usr/share/litesoftware; fi

# Add Skype for Linux Signed Key
if [ -f "/usr/bin/skypeforlinux" ]; then
curl https://repo.skype.com/data/SKYPE-GPG-KEY | sudo apt-key add -;
else :; fi
